spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kylin?useUnicode=true&characterEncoding=UTF-8&useSSL=false

    username: root
    password: 123
    # 可省略驱动配置, sprin-boot 会由url检测出驱动类型
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456      # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.example.demo.entity
  configuration:
    mapUnderscoreToCamelCase: true
gk:
  name: test
  age: 18
uploadFilePath: G:\file